health:
  config:
    enabled: false
spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  aop:
    auto: true
    proxy-target-class: true
  jackson:
    default-property-inclusion: non_null
    mapper:
      default-view-inclusion: true
    deserialization:
      adjust-dates-to-context-time-zone: false
      fail-on-unknown-properties: false
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
  cloud:
    stream:
      bindings:
        springCloudBusOutput:
          destination: springCloudBus
        springCloudBusInput:
          destination: springCloudBus
server:
  port: 8080
  tomcat:
    max-threads: 10
management:
  port: 9999
  security:
    enabled: false
  ssl:
    enabled: false
ws:
  context:
    clientCode: 281
  security:
    username: SBIPv2
    signature:
      parts: "{}{http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd}UsernameToken;{}{http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd}Timestamp;{}{http://schemas.xmlsoap.org/soap/envelope/}Body;{}{http://www.nbfg.ca/fw/serviceHeaders}serviceContext;{}{http://www.w3.org/2005/08/addressing}MessageID;{}{http://www.w3.org/2005/08/addressing}Action;{}{http://www.w3.org/2005/08/addressing}To"
hystrix:
  metrics:
    enabled: false
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
            interruptOnTimeout: true
  stream:
    send-id: false
    queue:
      sendRate: 5000
      gatherRate: 1000
logging:
  config: "//mnt/cfg/log4j2.xml"
helper:
  mask:
    clientCard: "dddddddddd*****dddd"
    masterCard: "************dddd"
security:
  config:
    admin:
      groups: Admin, SuperHero, Robot
    agent:
      groups: Agent, OtherAgent
    retail:
      groups: Client.Retail, SomeOtherRetail
    session-id-header: SESSION_ID
