spring:
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: sbcpc-config-consumer
management:
  security:
    enabled: false
server:
  port: 9999
health:
  config:
    enabled: false
